# Splunk App Configuration File
# See http://docs.splunk.com/Documentation/Splunk/latest/Admin/Appconf for details

[install]
is_configured = 1
state = enabled
build = 100

[ui]
is_visible = 1
label = Aegis-Mind Agentic NOC
show_in_nav = 1

[launcher]
author = Aegis-Mind Contributors
description = Autonomous Multi-Agent NOC for Incident Response and SecOps using Google Antigravity SDK & Model Context Protocol.
version = 1.0.0

[package]
id = aegis_mind
check_for_updates = 0
