# Splunk Custom Search Command Configuration
# See http://docs.splunk.com/Documentation/Splunk/latest/Admin/Commandsconf for details

[aegismind]
filename = aegis_search_command.py
chunked = true
python.version = python3
supports_getinfo = true
supports_rawargs = true
